# SPDX-License-Identifier: Apache-2.0

[workspace]
resolver = "3"
members = [
  "lib",
  "cli",
  "server",
  "wasm",
]

[workspace.dependencies]
hakanai-lib = { path = "lib", version = "3.0.0" }

[profile.release]
opt-level = "z"
lto = true
